# Generated by Django 5.1.5 on 2026-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='facing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='foots',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='sqft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APART', 'Apartment'), ('PLOT', 'Plot'), ('1BHK', '1Bhk'), ('2BHK', '2Bhk'), ('3BHK', '3Bhk'), ('PG', 'PG'), ('VILLA', 'Villa'), ('FLAT', 'Flat'), ('INDUS_PLOT', 'Industrial Plot'), ('SHOP', 'Shop'), ('INDUS_BUILDING', 'Industrial Building'), ('SHOWROOM_SCO', 'Showroom/SCO')], default='HOUSE', max_length=50),
        ),
    ]
