# Generated by Django 5.1.5 on 2026-05-01 20:11

import django.core.validators
import tweet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rental',
            name='contact',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits).', regex='^\\+?\\d{10,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits).', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(upload_to='rental_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('PG', 'PG'), ('VILLA', 'Villa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rentalimage',
            name='image',
            field=models.ImageField(upload_to='rental_gallery/%Y/%m/', validators=[tweet.models.validate_image_size]),
        ),
    ]
