# Generated by Django 5.1.5 on 2026-04-26 15:45

import django.core.validators
import django.db.models.deletion
import tweet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_rental_address_rental_facing_rental_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(upload_to='rental_images/', validators=[tweet.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_gallery/', validators=[tweet.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tweet.rental')),
            ],
        ),
    ]
