# Generated by Django 5.1.5 on 2026-04-27 06:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tweet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_rental_image_rentalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rentalimage',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='foots',
        ),
        migrations.AddField(
            model_name='rentalimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='facing',
            field=models.CharField(blank=True, help_text='e.g., North, East-Facing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='floor',
            field=models.CharField(blank=True, help_text='e.g., Ground, 2nd, Top', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(upload_to='rental_images/%Y/%m/', validators=[tweet.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('PG', 'PG / Co-Living'), ('FLAT', 'Flat'), ('VILLA', 'Villa'), ('PLOT', 'Residential Plot'), ('SHOP', 'Commercial Shop'), ('OFFICE', 'Office Space'), ('SHOWROOM', 'Showroom / SCO'), ('INDUS_BUILDING', 'Industrial Building'), ('INDUS_PLOT', 'Industrial Plot')], db_index=True, default='HOUSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Total area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(help_text='Catchy title for the listing', max_length=150),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalimage',
            name='image',
            field=models.ImageField(upload_to='rental_gallery/%Y/%m/', validators=[tweet.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['price', 'property_type'], name='tweet_renta_price_a27c01_idx'),
        ),
    ]
