# Generated by Django 5.1.5 on 2026-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_customuser_managers_alter_rental_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
