# Generated by Django 5.1.5 on 2026-04-27 07:04

import django.core.validators
import tweet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_customuser_options_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterModelOptions(
            name='rentalimage',
            options={'verbose_name': 'Gallery Photo', 'verbose_name_plural': 'Gallery Photos'},
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='tweet_renta_price_a27c01_idx',
        ),
        migrations.AddField(
            model_name='rental',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=False, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.TextField(verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='facing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Facing Direction'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Floor No.'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(upload_to='rental_images/%Y/%m/', validators=[tweet.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Main Thumbnail'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='location',
            field=models.CharField(db_index=True, max_length=255, verbose_name='City/Area'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Area (Sq. Ft)'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Property Title'),
        ),
        migrations.AlterField(
            model_name='rentalimage',
            name='image',
            field=models.ImageField(upload_to='rental_gallery/%Y/%m/', validators=[tweet.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Gallery Image'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['price', 'property_type', 'location'], name='tweet_renta_price_d47428_idx'),
        ),
    ]
