# Generated by Django 5.1.5 on 2026-05-08 14:51

import cloudinary_storage.storage
import tweet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_rental_bathrooms_rental_bedrooms_rental_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='rentals/', validators=[tweet.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('PG', 'PG'), ('VILLA', 'Villa'), ('SHOWROOM', 'Showroom'), ('INDUSTRIAL_PLOT', 'Industrial Plot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='rental_gallery/'),
        ),
    ]
