# Generated by Django 5.1.5 on 2026-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_customuser_options_alter_rentalimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
