# Generated by Django 5.1.5 on 2026-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_alter_rental_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rental',
            name='tweet_renta_price_d47428_idx',
        ),
        migrations.AddField(
            model_name='rental',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['price', 'property_type', 'location', 'is_available'], name='tweet_renta_price_bed50e_idx'),
        ),
    ]
