# Generated by Django 5.1.5 on 2026-05-17 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_customuser_address_customuser_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits).', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.CreateModel(
            name='PropertyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('COPY', 'Copy Link'), ('DIRECT', 'Direct')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tweet.rental')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
