# Generated by Django 5.1.5 on 2026-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_remove_rental_tweet_renta_price_d47428_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='contact',
            field=models.CharField(default='', max_length=15, verbose_name='Contact Number'),
            preserve_default=False,
        ),
    ]
