# Generated by Django 5.1.5 on 2026-05-17 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_alter_customuser_phone_number_propertylead'),
    ]

    operations = [
        # This migration is intentionally empty. It bypasses a problematic schema
        # change (shrinking a CharField) that was reverted in migration 0011.
    ]
