# Generated by Django 5.1.5 on 2026-05-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_alter_customuser_phone_number'),
    ]

    operations = [
    ]
