# Generated by Django 5.1.5 on 2026-05-17 10:55

from django.db import migrations
from django.db.models.functions import Length


def truncate_phone_numbers(apps, schema_editor):
    """
    Finds and truncates any CustomUser.phone_number fields that are longer
    than 15 characters to ensure data integrity with the model's max_length.
    """
    CustomUser = apps.get_model('tweet', 'CustomUser')
    db_alias = schema_editor.connection.alias

    # Using the ORM, filter for users with phone numbers longer than 15 characters.
    # The Length function is database-agnostic and works on both PostgreSQL and SQLite.
    users_to_update = CustomUser.objects.using(db_alias).annotate(
        phone_len=Length('phone_number')
    ).filter(phone_len__gt=15)

    for user in users_to_update.iterator():
        user.phone_number = user.phone_number[:15]
        user.save(update_fields=['phone_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_propertyshare_data_migration'),
    ]

    operations = [
        migrations.RunPython(truncate_phone_numbers, reverse_code=migrations.RunPython.noop),
    ]