# Generated by Django 5.1.5 on 2026-05-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_propertyshare_data_migration'),
    ]

    operations = [
    ]
