# Generated by Django 5.1.5 on 2026-05-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_truncate_long_phone_numbers'),
        ('tweet', '0014_fix_phone_number_manually'),
    ]

    operations = [
    ]
