# Generated by Django 5.1.5 on 2026-05-20 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0015_merge_20260517_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='user',
        ),
        migrations.AlterField(
            model_name='propertyshare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='propertyshare',
            index=models.Index(fields=['user', 'created_at'], name='tweet_prope_user_id_b037a6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyshare',
            index=models.Index(fields=['property', 'created_at'], name='tweet_prope_propert_7cbba4_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyshare',
            index=models.Index(fields=['platform', 'created_at'], name='tweet_prope_platfor_439c61_idx'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='tweet.rental'),
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='tweet.propertyshare'),
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry', to='tweet.propertyvisit'),
        ),
        migrations.DeleteModel(
            name='PropertyLead',
        ),
        migrations.AddIndex(
            model_name='propertyvisit',
            index=models.Index(fields=['share', 'visited_at'], name='tweet_prope_share_i_9e1c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['property', 'created_at'], name='tweet_prope_propert_fdf64b_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['visit'], name='tweet_prope_visit_i_295213_idx'),
        ),
    ]
