# Generated by Django 5.1.5 on 2026-05-20 14:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0016_propertyinquiry_propertyvisit_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='propertyinquiry',
            name='tweet_prope_propert_fdf64b_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyinquiry',
            name='tweet_prope_visit_i_295213_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyshare',
            name='tweet_prope_user_id_b037a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyshare',
            name='tweet_prope_propert_7cbba4_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyshare',
            name='tweet_prope_platfor_439c61_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyvisit',
            name='tweet_prope_share_i_9e1c4c_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('BROKER', 'Broker'), ('OWNER', 'Owner'), ('SEEKER', 'Seeker')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('PG', 'PG'), ('VILLA', 'Villa'), ('SHOWROOM', 'Showroom'), ('INDUSTRIAL_PLOT', 'Industrial Plot')], max_length=30),
        ),
    ]
