# Generated by Django 5.1.5 on 2026-06-04 18:24

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0018_update_site_domain'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='wishlisted_by',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('PG', 'PG'), ('VILLA', 'Villa'), ('SHOWROOM', 'Showroom'), ('INDUSTRIAL_PLOT', 'Industrial Plot')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['is_available', '-created_at'], name='rental_avail_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['property_type', 'is_available', '-created_at'], name='rental_type_avail_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['user', '-created_at'], name='rental_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['is_available', 'price'], name='rental_avail_price_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='rental_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='rental_location_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='rental_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
