# Generated by Django 5.1.5 on 2026-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0019_alter_customuser_managers_rental_wishlisted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]